config/routes.rb
Rails.application.routes.draw do
  resources :disasters

  root 'disasters#index'

end

app/models/disaster.rb
require 'faraday'
require 'json'

class Disaster < ActiveRecord::Base

  def self.list_all
    request_disasters
  end

  private

  def self.request_disasters
    @conn = Faraday.new(:url => "http://api.rwlabs.org")
    response = @conn.get "/v1/reports"
    # Unirest::get "http://api.rwlabs.org/v1/reports"
    JSON.parse(response.body, symbolize_names:true)[:data]
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/disasters_controller.rb
class DisastersController < ApplicationController
  before_action :set_disaster, only: [:show, :edit, :update, :destroy]

  # GET /disasters
  # GET /disasters.json
  def index
    @disasters = Disaster.list_all
  end

  # GET /disasters/1
  # GET /disasters/1.json
  def show
  end

  # GET /disasters/new
  def new
    @disaster = Disaster.new
  end

  # GET /disasters/1/edit
  def edit
  end

  # POST /disasters
  # POST /disasters.json
  def create
    @disaster = Disaster.new(disaster_params)

    respond_to do |format|
      if @disaster.save
        format.html { redirect_to @disaster, notice: 'Disaster was successfully created.' }
        format.json { render :show, status: :created, location: @disaster }
      else
        format.html { render :new }
        format.json { render json: @disaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /disasters/1
  # PATCH/PUT /disasters/1.json
  def update
    respond_to do |format|
      if @disaster.update(disaster_params)
        format.html { redirect_to @disaster, notice: 'Disaster was successfully updated.' }
        format.json { render :show, status: :ok, location: @disaster }
      else
        format.html { render :edit }
        format.json { render json: @disaster.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /disasters/1
  # DELETE /disasters/1.json
  def destroy
    @disaster.destroy
    respond_to do |format|
      format.html { redirect_to disasters_url, notice: 'Disaster was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_disaster
      @disaster = Disaster.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def disaster_params
      params.require(:disaster).permit(:name, :date, :country, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/disasters_helper.rb
module DisastersHelper
end

app/views/disasters/_form.html.erb
<%= form_for(@disaster) do |f| %>
  <% if @disaster.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@disaster.errors.count, "error") %> prohibited this disaster from being saved:</h2>

      <ul>
      <% @disaster.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
    <%= f.label :country %><br>
    <%= f.text_field :country %>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/disasters/edit.html.erb
<h1>Editing disaster</h1>

<%= render 'form' %>

<%= link_to 'Show', @disaster %> |
<%= link_to 'Back', disasters_path %>

app/views/disasters/index.html.erb
<h1>Ten Most Recent Disasters</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Title</th>
      <th>Country</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <%= @disasters %>

  <tbody>
    <% @disasters.each do |disaster| %>
      <tr>
        <td><%= disaster[:id] %></td>
        <td><%= disaster[:fields][:title] %></td>
        <td><%= link_to 'Show', disaster[:href] %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Disaster', new_disaster_path %>

app/views/disasters/new.html.erb
<h1>New disaster</h1>

<%= render 'form' %>

<%= link_to 'Back', disasters_path %>

app/views/disasters/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @disaster.name %>
</p>

<p>
  <strong>Date:</strong>
  <%= @disaster.date %>
</p>

<p>
  <strong>Country:</strong>
  <%= @disaster.country %>
</p>

<p>
  <strong>Description:</strong>
  <%= @disaster.description %>
</p>

<%= link_to 'Edit', edit_disaster_path(@disaster) %> |
<%= link_to 'Back', disasters_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DisasterRelief</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>